"""add worklog payment domain

Revision ID: 0f87ea222625
Revises: 1a31ce608336
Create Date: 2026-03-18 16:02:48.522723

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f87ea222625'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancer_created_at'), 'freelancer', ['created_at'], unique=False)
    op.create_index(op.f('ix_freelancer_email'), 'freelancer', ['email'], unique=True)
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_created_at'), 'payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_table('worklog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('freelancer_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worklog_created_at'), 'worklog', ['created_at'], unique=False)
    op.create_index(op.f('ix_worklog_freelancer_id'), 'worklog', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_worklog_status'), 'worklog', ['status'], unique=False)
    op.create_index(op.f('ix_worklog_task_id'), 'worklog', ['task_id'], unique=False)
    op.create_table('paymentworklog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('worklog_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentworklog_payment_id'), 'paymentworklog', ['payment_id'], unique=False)
    op.create_index(op.f('ix_paymentworklog_worklog_id'), 'paymentworklog', ['worklog_id'], unique=False)
    op.create_table('timeentry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worklog_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeentry_worklog_id'), 'timeentry', ['worklog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeentry_worklog_id'), table_name='timeentry')
    op.drop_table('timeentry')
    op.drop_index(op.f('ix_paymentworklog_worklog_id'), table_name='paymentworklog')
    op.drop_index(op.f('ix_paymentworklog_payment_id'), table_name='paymentworklog')
    op.drop_table('paymentworklog')
    op.drop_index(op.f('ix_worklog_task_id'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_status'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_freelancer_id'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_created_at'), table_name='worklog')
    op.drop_table('worklog')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_created_at'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_freelancer_email'), table_name='freelancer')
    op.drop_index(op.f('ix_freelancer_created_at'), table_name='freelancer')
    op.drop_table('freelancer')
    # ### end Alembic commands ###
