/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutWorklogsRouteImport } from './routes/_layout/worklogs'
import { Route as LayoutWorklogsIndexRouteImport } from './routes/_layout/worklogs.index'
import { Route as LayoutWorklogsWorklogIdRouteImport } from './routes/_layout/worklogs.$worklogId'
import { Route as LayoutPaymentsPaymentIdRouteImport } from './routes/_layout/payments.$paymentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorklogsRoute = LayoutWorklogsRouteImport.update({
  id: '/worklogs',
  path: '/worklogs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorklogsIndexRoute = LayoutWorklogsIndexRouteImport.update({
  id: '/worklogs/',
  path: '/',
  getParentRoute: () => LayoutWorklogsRoute,
} as any)
const LayoutWorklogsWorklogIdRoute = LayoutWorklogsWorklogIdRouteImport.update({
  id: '/worklogs/$worklogId',
  path: '/$worklogId',
  getParentRoute: () => LayoutWorklogsRoute,
} as any)
const LayoutPaymentsPaymentIdRoute = LayoutPaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/worklogs': typeof LayoutWorklogsRouteWithChildren
  '/worklogs/': typeof LayoutWorklogsIndexRoute
  '/worklogs/$worklogId': typeof LayoutWorklogsWorklogIdRoute
  '/payments/$paymentId': typeof LayoutPaymentsPaymentIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/worklogs': typeof LayoutWorklogsIndexRoute
  '/worklogs/$worklogId': typeof LayoutWorklogsWorklogIdRoute
  '/payments/$paymentId': typeof LayoutPaymentsPaymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/worklogs': typeof LayoutWorklogsRouteWithChildren
  '/_layout/worklogs/': typeof LayoutWorklogsIndexRoute
  '/_layout/worklogs/$worklogId': typeof LayoutWorklogsWorklogIdRoute
  '/_layout/payments/$paymentId': typeof LayoutPaymentsPaymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/worklogs'
    | '/worklogs/'
    | '/worklogs/$worklogId'
    | '/payments/$paymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/worklogs'
    | '/worklogs/$worklogId'
    | '/payments/$paymentId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/worklogs'
    | '/_layout/worklogs/'
    | '/_layout/worklogs/$worklogId'
    | '/_layout/payments/$paymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/worklogs': {
      id: '/_layout/worklogs'
      path: '/worklogs'
      fullPath: '/worklogs'
      preLoaderRoute: typeof LayoutWorklogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/worklogs/': {
      id: '/_layout/worklogs/'
      path: '/'
      fullPath: '/worklogs/'
      preLoaderRoute: typeof LayoutWorklogsIndexRouteImport
      parentRoute: typeof LayoutWorklogsRoute
    }
    '/_layout/worklogs/$worklogId': {
      id: '/_layout/worklogs/$worklogId'
      path: '/$worklogId'
      fullPath: '/worklogs/$worklogId'
      preLoaderRoute: typeof LayoutWorklogsWorklogIdRouteImport
      parentRoute: typeof LayoutWorklogsRoute
    }
    '/_layout/payments/$paymentId': {
      id: '/_layout/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof LayoutPaymentsPaymentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutWorklogsRouteChildren {
  LayoutWorklogsIndexRoute: typeof LayoutWorklogsIndexRoute
  LayoutWorklogsWorklogIdRoute: typeof LayoutWorklogsWorklogIdRoute
}

const LayoutWorklogsRouteChildren: LayoutWorklogsRouteChildren = {
  LayoutWorklogsIndexRoute: LayoutWorklogsIndexRoute,
  LayoutWorklogsWorklogIdRoute: LayoutWorklogsWorklogIdRoute,
}

const LayoutWorklogsRouteWithChildren =
  LayoutWorklogsRoute._addFileChildren(LayoutWorklogsRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutWorklogsRoute: typeof LayoutWorklogsRouteWithChildren
  LayoutPaymentsPaymentIdRoute: typeof LayoutPaymentsPaymentIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutWorklogsRoute: LayoutWorklogsRouteWithChildren,
  LayoutPaymentsPaymentIdRoute: LayoutPaymentsPaymentIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
